### ISSUE TITLE
Multiple Entries per Song after fresh creation

### ISSUE THREAD

**Issue by KaeTuuN** [ampache/ampache-docker#109]
Seems related to https://github.com/ampache/ampache/issues/1374

Created completely from scratch and lots of Songs got added 2 - 6 times.

Added catalogue Soundtracks, everthing was fine.
Added catalogue Sampler and nearly every song got added at least two times.
Stopped adding further catalogues.

Catalogue differences:
| Value | Soundtracks | Sampler |
| --- | --- | --- |
| added | first | second |
|albums | 20 | 150 | 
| filenames | %a - %T - %t | %T - %a - %t |

Here is my docker-compose file, created with https://github.com/Red5d/docker-autocompose
```
services:
  ampache:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    command:
      - "run.sh"

    container_name: "ampache"

    entrypoint:
      - "docker-entrypoint.sh"

    environment:
      - "UID=1001"
      - "GID=1001"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "DEBIAN_FRONTEND=noninteractive"
      - "MYSQL_PASS=**Random**"

    hostname: "2944f0aa4bec"

    image: "ampache/ampache:latest"

    ipc: "private"

    labels:
      maintainer: "lachlan-00"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "<removed>"

    network_mode: "<removed>"

    ports:
      - "<removed>:80/tcp"

    restart: "unless-stopped"

    volumes:
      - "/srv/data/audiobooks:/media/audiobooks"
      - "/srv/data/music:/media/music"
      - "/srv/data/sampler:/media/sampler"
      - "/srv/data/soundtracks:/media/soundtracks"
      - "966330e2982f359c2eafe1f992a9dfc30001c7f3a9b227be2ce1793e5144ca42:/etc/mysql"
      - "ampache_config:/var/www/config"
      - "ampache_log:/var/log/ampache"
      - "ampache_sql:/var/lib/mysql"

version: "3.6"

volumes:
  966330e2982f359c2eafe1f992a9dfc30001c7f3a9b227be2ce1793e5144ca42:
    external: true
  ampache_config:
    external: true
  ampache_log:
    external: true
  ampache_sql:
    external: true
```
