### ISSUE TITLE
Setting web_path results in 404 after setup

### ISSUE THREAD

**Issue by calebjones** [ampache/ampache-docker#120]
Docker Compose:

```
version: '3'

services:
  ampache:
    image: ampache/ampache:nosql
    container_name: ampache
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - /host/path/to/music:/media
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

Startup command:

```
docker compose up -d
```

Database connects properly to my host and I am able to have this work (build catalog, stream music, etc) without setting `web_path` in the setup web UI.

However, if I set the `web_path` in the web UI to (for example) `/ampache`, after the setup completes, it only ever returns 404 for `/ampache` or `/` (also tried `/ampache/index.php` or `/ampache/login.php`.
