### ISSUE TITLE
To create volume folders or not to

### ISSUE THREAD

**Issue by 75th** [ampache/ampache-docker#125]
I have the exact same problem as #24, but with a twist. I'm trying to use the docker-compose file in Container Manager in Synology DSM. If I create the data folders ahead of time, I get the same "Waiting for confirmation of MySQL service startup" loop as in #24, which says to simply not create them ahead of time. But if I don't, I get this error:

```Bind mount failed: '/volume1/Ampache/data/mysql' does not exists```

([*sic*] on "exists")

I went looking to learn more about Docker stuff to understand this issue, and I immediately found [this](https://docs.docker.com/storage/volumes/):

> Volumes have several advantages over bind mounts:

So the docs say volumes are an alternative to bind mounts, but I'm getting bind mount errors when trying to use volumes. At this point I threw up my hands and came here. By all means tell me if I should go bug the Synology forum, but the Synology forum is pretty useless in my experience, and I thought maybe there's a chance this is still Ampache-specific.

Here's the docker-compose YAML I'm using. Changed a port and omitted the last line, which DSM didn't like.

<details>
<summary>My docker-compose</summary>

```
version: '3'

services:
  ampache:
    image: ampache/ampache:latest
    container_name: ampache
    restart: unless-stopped
    ports:
      - 50180:80
    volumes:
      - ./data/config:/var/www/config
      - ./data/log:/var/log/ampache
      - ./data/media:/media
      - ./data/mysql:/var/lib/mysql
```
</details>
