### ISSUE TITLE
Allow use of an external mysql server

### ISSUE THREAD

**Issue by xordspar0** [ampache/ampache-docker#16]
Instead of using a mysql server inside the container and controlling the /var/lib/mysql directory on the host machine, ampache-docker should support using a mysql server running on the host machine or another container, possibly with an optional docker-compose.yaml.

**Comment by lachlan-00** [comment]
you can use a separate mysql server already.

I've just added a config import in pull #26 set your database up there and it will use your external server.

**Comment by shikasta-net** [comment]
Related to this, I'd like to find a clean way to switch off the internal mysql server when not needed.  I'll make a PR once I've found something that works.

What do you think about changing the apache service to foreground and wiring `if env.DBhost` to set the parameter in the config and not enable the sqld?

**Comment by lachlan-00** [comment]
Yeah i was thinking the same thing. If you set an ENV don't do the RUN parts for mysql.

I'm not sure about the exact way to do it but the dockerfile must be able to do/ignore run commands based on variables.

**Comment by lachlan-00** [comment]
Seems like it's done with a build arg
https://stackoverflow.com/questions/43654656/dockerfile-if-else-condition-with-external-arguments#43656644

Then i can just make a tag like ampache/ampache:nosql

**Comment by shikasta-net** [comment]
That could work and would make the image smaller.  I had actually been thinking of making the changes within _run.sh_: moving the services around and wrapping the creation of the SQL workspace and starting the service inside something that checked if a DB_HOST was set in the ENV, with the alternative being to `sed` the config file line to set the database host accordingly.  

If you have a plan and point me to a PR I'd be happy to test and review it.  I probably won't get around to implementing my own solution for a few weeks anyway so you may get there first.

**Comment by lachlan-00** [comment]
I've just started on this and i'll be building to try it out soon. I'll make a build tagged as ampache/ampache:nosql based on master only.

all it does is build based on a build argument nosql (--build-arg nosql=1)
```
 => [6/8] RUN     if [ "x$nosql" = "x" ] ; then INSTALL SQL
```

It just requires an edit to run.sh to execute bash instead of mysql and i'm done.

**Comment by kuzi-moto** [comment]
I don't know how this would impact existing users of the Docker image, but I think it would be better if Ampache defaulted to not including the DB in the image. I'm not even sure we should offer an image with the DB, just provide instructions for using Docker Compose to start Ampache with a separate DB image.

**Comment by YasserAntonio** [comment]
Could someone provide they way this can be configured ? Since I have this issue: #43  with the internal mysql db. Thanks !

**Comment by kuzi-moto** [comment]
How familiar are you with Docker? With docker-compose you can easily specify a separate MySQL server and then use that when installing Ampache. If you need further guidance I'd be happy to provide a sample config. It's just the built in MySQL would sti be running.

**Comment by YasserAntonio** [comment]
Thanks @kuzi-moto !  I'm a noob with docker. 

basically i know it would look something like this : 

```
services:
  db:
    image: biarms/mysql:5.7.30-beta-travis
    environment:
      MYSQL_USER: ampache
      MYSQL_PASSWORD: XXXX
      MYSQL_ROOT_PASSWORD: XXXX
      MYSQL_DATABASE: ampache
    volumes:
      - /home/pi/ampache/mysql:/var/lib/mysql
    restart: unless-stopped
  music_center:
    hostname: ampache.ln
    restart: unless-stopped
    image: ampache/ampache:latest
    volumes:
      - /home/pi/ampache/config:/var/www/config
      - /home/pi/ampache/sites-enabled:/etc/apache2/sites-enabled
      - /home/pi/musics:/media
    ports:
      - 8081:80
      depends_on:
      - db
```

but still I dont get how apache will know that he must use the external mysql server.
