### ISSUE TITLE
Ampache Docker on Raspberry Pi 4 - Ubuntu Server 18.04 - NextcloudPi in External HDD, Can login with in Android with Just Player, Can't login in Android with Power Ampache or UltraSonic

### ISSUE THREAD

**Issue by qwertyuser1983** [ampache/ampache-docker#37]
I am using Ampache Docker on a Raspberry Pi 4 with Ubuntu Server 18.04 installed. All music and videos reside in a NextCloudPi data folder. 

My docker compose.yml

```
version: "2"
services:
  ampache:
    image: ampache/ampache
    container_name: ampache
    volumes:
      - [externalhdd]/NextCloudPi/Data/nextcloud/data/[username]/files/[path]/Media:/media:ro
    ports:
      - [port]:80
    restart: unless-stopped
```
I can login with Android - Just Player or any browser, but I failed to login using Android - Power Ampache or Android - UltraSonic.

Thanks before.
