### ISSUE TITLE
(NoSQL) cannot get past step 2, config/ampache.cfg.php cannot be written

### ISSUE THREAD

**Issue by mrzapp** [ampache/ampache-docker#64]
I know several other issues have been created on this topic, but none of them seem to solve this issue.

I am trying to run Ampache in a Docker container without a database (I am using Postgres, and Ampache doesn't seem to support that, so it seems like my only option)

At step 1, this is what I see:
* Even though I picked the `:nosql` image, there are input fields for database credentials present
* It also lists a MySQL database as a requirement
* The step itself is even called "Create the Ampache database"
* Everything else checks out (I manually downloaded and placed the [ampache.cfg.php.dist](https://github.com/ampache/ampache-docker/blob/master/data/config/ampache.cfg.php.dist) file in the `/var/www/config` dir, which is owned by `www-data:www-data`)

At step 2, this is what I see:
* Error: Invalid configuration settings. Configuration files were either not found or unreadable
* config/ampache.cfg.php action: Download/write buttons do nothing, they just reload the page
* Manually creating the `ampache.cfg.php` based on the `ampache.cfg.php.dist` just seems to make Ampache assume that I want to use a database, but didn't provide the correct credentials
* There are no error messages in the docker log

This is the relevant section of my `docker-compose.yml`:

```yml
ampache:
    image: ampache/ampache:nosql
    restart: always
    ports:
        - "1002:80"
    volumes:
        - "./ampache/config:/var/www/config" # This is owned by www-data:www-data both on the host and in the container
        - "/my/music/folder:/media:ro"
```

Is there an example config file for `nosql` that I can copy to the `/var/www/config` dir as a quick solution for now?
